version: 3

vars:
  TARGET_DIR: target
  VERSION:
    sh: test -n "${VERSION}" && echo "${VERSION}"
  LD_FLAGS: '{{default "-w -s" .LD_FLAGS}}'
  DATE_BUILT: '{{now | date "2006-01-02T15:04:05Z"}}'
  GO_BUILD_CMD: go build {{.GO_FLAGS}} -trimpath -tags "{{.TAGS}}" -ldflags "{{.LD_FLAGS}} -X main.Version={{.VERSION}} -X main.DateBuilt={{.DATE_BUILT}}"

tasks:
  build:
    desc: Build language server
    env:
      CGO_ENABLED: 0
    deps:
      - for: { matrix: { OS: [linux, darwin, windows], ARCH: [amd64, arm64] } }
        task: build:target
        vars:
          OS: "{{.ITEM.OS}}"
          ARCH: "{{.ITEM.ARCH}}"

  build:target:
    desc: Build language server for a specific OS and architecture
    env:
      CGO_ENABLED: 0
    preconditions:
      - sh: test -n "{{.OS}}"
        msg: Required build variable OS is not set
      - sh: test -n "{{.ARCH}}"
        msg: Required build variable ARCH is not set
    vars:
      BIN: "language-server-{{.VERSION}}-{{.OS}}-{{.ARCH}}"
      EXT: '{{if eq .OS "windows"}}.exe{{end}}'
    cmds:
      - cmd: "GOOS={{.OS}} GOARCH={{.ARCH}} {{.GO_BUILD_CMD}} -o {{.TARGET_DIR}}/{{.BIN}}{{.EXT}} ./cmd/cli/main.go"
      - if: '{{ eq .OS "windows" }}'
        cmd: zip -j {{.TARGET_DIR}}/{{.BIN}}.zip {{.TARGET_DIR}}/{{.BIN}}{{.EXT}}
      - if: '{{ ne .OS "windows" }}'
        cmd: tar -czvf {{.TARGET_DIR}}/{{.BIN}}.tar.gz -C {{.TARGET_DIR}} {{.BIN}}
      - cmd: rm -f {{.TARGET_DIR}}/{{.BIN}}{{.EXT}}
